<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="leomahesh-PC" ignored="0" name="Encor-E Application Test Cases" tests="9" failures="1" timestamp="07 Nov 2019 06:35:16 GMT" time="71.985" errors="0">
  <testcase name="VerifyReportingPageTitle" time="0.024" classname="com.encore.testcases.ReportingPage_TestCases"/>
  <testcase name="ClickOn_Reporting_Test" time="0.732" classname="com.encore.testcases.ReportingPage_TestCases"/>
  <testcase name="Display_All_ReportingMenu_Test" time="3.049" classname="com.encore.testcases.ReportingPage_TestCases"/>
  <testcase name="Display_HospMenu_Test" time="0.537" classname="com.encore.testcases.ReportingPage_TestCases">
    <skipped/>
  </testcase> <!-- Display_HospMenu_Test -->
  <testcase name="Display_HospMenu_Test" time="2.307" classname="com.encore.testcases.ReportingPage_TestCases">
    <skipped/>
  </testcase> <!-- Display_HospMenu_Test -->
  <testcase name="Display_HospMenu_Test" time="0.574" classname="com.encore.testcases.ReportingPage_TestCases">
    <skipped/>
  </testcase> <!-- Display_HospMenu_Test -->
  <testcase name="Display_HospMenu_Test" time="0.746" classname="com.encore.testcases.ReportingPage_TestCases">
    <skipped/>
  </testcase> <!-- Display_HospMenu_Test -->
  <testcase name="Display_HospMenu_Test" time="0.528" classname="com.encore.testcases.ReportingPage_TestCases">
    <failure type="java.lang.AssertionError" message="Expected is : Hospital Measures: TestCase Failed !!! expected [Hospital Measures] but found [Hospital Measure]">
      <![CDATA[java.lang.AssertionError: Expected is : Hospital Measures: TestCase Failed !!! expected [Hospital Measures] but found [Hospital Measure]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.encore.testcases.ReportingPage_TestCases.Display_HospMenu_Test(ReportingPage_TestCases.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- Display_HospMenu_Test -->
  <testcase name="Display_EH_MenuList_Test" time="0.443" classname="com.encore.testcases.ReportingPage_TestCases"/>
</testsuite> <!-- Encor-E Application Test Cases -->
